### ISSUE TITLE
InfluxDB not written to disk

### ISSUE THREAD

**Issue by invertium** [philhawthorne/docker-influxdb-grafana#33]
I started the container and wrote a bunch of data to it. After killing the container and restarting it all the data was gone. Any idea why? 

Heres my dockerfile:

```
version: '3'
services:
  mongo:
    ports:
      - "27017:27017"
    volumes:
      - .dockerdata/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    image: mongo
  grafana-influx:
    ports:
      - "3003:3003"
#      - "3004:8083"
      - "8086:8086"
    volumes:
      - .dockerdata/influxdb:/var/lib/influxdb
      - .dockerdata/grafana:/var/lib/grafana
    image: philhawthorne/docker-influxdb-grafana:latest
```
