### ISSUE TITLE
Chronograf config resetting over and over

### ISSUE THREAD

**Issue by hyacin75** [philhawthorne/docker-influxdb-grafana#38]
Hey hey,

Awesome container, thank you so much.  Got it up and running np, feeding data in, I can access everything, it's great.

Every time I go to my Chronograf tab though, it's on the "Welcome to Chronograf" screen again and wanting me to set it up.  I'm assuming the container has restarted since I last looked at the tab (I'll pay more attention next time) and that perhaps some persistence is missing?  Here's my swarm conf -

```
version: "3.3"

services:
  AIO:
    image: philhawthorne/docker-influxdb-grafana:latest
    volumes:
     - type: volume
       source: influxdb
       target: /var/lib/influxdb
       volume:
         nocopy: true
     - type: volume
       source: grafana
       target: /var/lib/grafana
       volume:
         nocopy: true
     - type: volume
       source: influxdb-conf
       target: /etc/influxdb
       volume:
         nocopy: true
    networks:
      - swarmnet
    environment:
      - TZ=America/New_York
    ports:
      - 3003:3003
      - 3004:8083
      - 8086:8086
      - 8089:8089/udp
    deploy:
      placement:
        constraints:
          - node.platform.arch==x86_64
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=swarmnet"
        - "traefik.chronograf.port=8083"
        - "traefik.chronograf.frontend.rule=Host:chronograf.cntr"
        - "traefik.grafana.port=3003"
        - "traefik.grafana.frontend.rule=Host:grafana.cntr"

networks:
  swarmnet:
    external:
      name: swarmnet

volumes:
  influxdb:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.55,nolock,soft,rw"
      device: ":/volume1/container_volumes/influxdb-grafana/influxdb"
  grafana:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.55,nolock,soft,rw"
      device: ":/volume1/container_volumes/influxdb-grafana/grafana"
  influxdb-conf:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.55,nolock,soft,rw"
      device: ":/volume1/container_volumes/influxdb-grafana/influxdb-conf"
```
