### ISSUE TITLE
InfluxDB enviroment variables

### ISSUE THREAD

**Issue by taserface987** [philhawthorne/docker-influxdb-grafana#55]
Does this image allows creation of influxdb by using enviroment variables like described [here](https://hub.docker.com/_/influxdb)?

```
version: "3.3"
 services:
  influxdb-grafana:
    image: philhawthorne/docker-influxdb-grafana:latest
    container_name: "influxdb-grafana"
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
    restart: always
    ports:
      - 3003:3003
      - 3004:8083
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
      - grafana:/var/lib/grafana
```

Here is part of my docker-compose file. From what I can see those variables are ignored.

**Comment by philhawthorne** [comment]
Hi @taserface987 

Unfortunately not at this time. For configuration, you'll need to edit the `/etc/influxdb/influxdb.conf` file inside the host.

You can do this by copying the `influxdb.conf` file from this repo, and then mounting it as a volume like the following:

```yaml
services:
  influxdb-grafana:
    image: philhawthorne/docker-influxdb-grafana:latest
    container_name: "influxdb-grafana"
    restart: always
    ports:
      - 3003:3003
      - 3004:8083
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
      - grafana:/var/lib/grafana
      - /path/to/influxdb.conf:/etc/influxdb/influxdb.conf
```
